CREATE DATABASE `SCRAPER_DB` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `SCRAPER_DB`.`WALLA_ITEMS` (
  `ID` int(11) NOT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `PRICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SCRAPER_DB`.`WALLA_SEARCHS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `KWS` varchar(45) NOT NULL,
  `DIST` int(11) NOT NULL DEFAULT '20',
  `MINPRICE` int(11) DEFAULT NULL,
  `MAXPRICE` int(11) DEFAULT NULL,
  `PUBLISHDATE` int(11) NOT NULL DEFAULT '24',
  `LONG` varchar(45) NOT NULL DEFAULT '-2.994161000000001',
  `LAT` varchar(45) NOT NULL DEFAULT '43.308567',
  `LAST` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `SCRAPER_DB`.`AMAZON_ITEMS` (
  `ID` int(11) NOT NULL,
  `ITEM_ID` varchar(100) DEFAULT NULL,
  `CHAT_ID` varchar(100) NOT NULL,
  `TITLE` varchar(1000) NOT NULL,
  `PRICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SCRAPER_DB`.`AMAZON_SEARCHS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` varchar(100) NOT NULL,
  `CHAT_ID` varchar(100) NOT NULL,
  `LAST` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;
