CREATE DATABASE `SCRAPER_DB` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `WALLA_ITEMS` (
  `ID` int(11) NOT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `PRICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `WALLA_SEARCHS` (
  `ID` int(11) NOT NULL,
  `KWS` varchar(45) NOT NULL,
  `DIST` int(11) DEFAULT NULL,
  `MINPRICE` int(11) DEFAULT NULL,
  `MAXPRICE` int(11) DEFAULT NULL,
  `PUBLISHDATE` int(11) NOT NULL,
  `LONG` varchar(45) NOT NULL,
  `LAT` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

